---
title: "SpringsFire_fuels"
author: "Ashley Grupenhoff"
date: "8/22/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
  library(tinytex)
          options(tinytex.verbose=TRUE)
library(tibble)
library(dplyr)
library(ggplot2)
library(vegan)
library(knitr)
library(kableExtra)
library(rio)
      
```

## Springs Fuel 

```{r}
springsfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/fuels/springsfuels_complete.csv")
SpringsFire_treatment <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/raw/springsfire_treatment.csv")
springs_litterduff_all <-  import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/fuels/springsfire_litterduff_consumption.csv")

#reorder
springsfuels$time <- factor(springsfuels$time, levels=c("preburn19_mass", "postburn19_mass"))


#convert to mg/ha

springsfuels <- springsfuels %>% 
  mutate(mass_mgha = mass*.446)

#add pre-post value

springsfuels_consumption <- springsfuels %>% 
  mutate(plotid_size = paste(plot_id, fuel_size, sep=" ")) %>% 
   select(plotid_size, time, mass_mgha) %>% 
  pivot_wider(names_from=time, values_from=mass_mgha) %>% 
  mutate(consumption = preburn_mass - postburn_mass) %>% 
  pivot_longer(-plotid_size, names_to = "time", values_to="mass_mgha") %>% 
  separate(plotid_size, c("plot_id", "size"), sep = " ") 

  springsfuelsconsumption <- left_join(springsfuels_consumption, SpringsFire_treatment, by="plot_id")

export(springsfuelsconsumption, "C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/springsfuels_consumption.csv")

springsfuelsconsumption <- springsfuelsconsumption %>% 
              filter(time== "consumption") 
  
springsfuels_consumption_plot <-   ggplot(data=springsfuelsconsumption, mapping = aes(x=treatment_type, y=mass_mgha))+
              geom_boxplot()+
              facet_wrap(~ size, scales = "free_y") +
              theme_minimal()+
              xlab("PriorTreatment")+
              ylab("Mass (Mg/Ha)")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
springsfuels_consumption_plot

```



```{r}
#1hr only

              springsfuels_1hr <- springsfuels %>% 
                filter(fuel_size == "mass_1hr")

#graph

springs_fuels_1hr <- ggplot(data=springsfuels_1hr, mapping = aes(x=treatment_type, y=mass, fill=time))+
              geom_boxplot()+
              scale_fill_manual(values=c("#69b3a2", "#404080"))+
              
              facet_wrap(~ fuel_size, scales = "free_y") +
              theme_minimal()+
              xlab("PriorTreatment")+
              ylab("Mass (Mg/Ha)")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
springs_fuels_1hr

#anova

group_by(springs_fuels_1hr, treatment_type) %>% 
  summarise(
    count=n(),
    mean = mean(mass_mgha, na.rm=TRUE),
    sd=sd(mass_mgha, na.rm=TRUE)
  )

```

