---
title: "Rx_Monitoring_InitialAnalyses"
author: "Ashley Grupenhoff"
date: "4/27/2020"
output: html_document
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
  library(tinytex)
          options(tinytex.verbose=TRUE)
library(tibble)
library(dplyr)
library(ggplot2)
library(vegan)
library(knitr)
library(kableExtra)
library(rio)
      
```

#importdata

```{r}
PreBurn_BMfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/clean/PreBurn_BMfuels.csv")
PreBurn_BMfuels <- PreBurn_BMfuels %>% 
  mutate(location = 'BearMtn')

PreBurn_FMfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/French_Meadows/data/clean/PreBurn_FMfuels.csv")
PreBurn_FMfuels <- PreBurn_FMfuels %>% 
  mutate(location = 'FrenchMeadows')


PreBurn_lakesfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Lakes_District/data/clean/prelakesfuels.csv")
PreBurn_lakesfuels <- PreBurn_lakesfuels %>% 
  mutate(location = 'LakesDistrict')

PreBurn_SlyParkFuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Sly_Park/data/clean/PreBurn_SlyParkfuels.csv")
PreBurn_SlyParkFuels <- PreBurn_SlyParkFuels %>% 
  mutate(location = 'SlyPark')

PreBurn_SpringsFire <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/prespringsfuels_complete.csv")
PreBurn_SpringsFire <- PreBurn_SpringsFire %>% 
  mutate(location = 'SpringsFire')



allfuels <- bind_rows(PreBurn_BMfuels, PreBurn_FMfuels, PreBurn_lakesfuels, PreBurn_SlyParkFuels, PreBurn_SpringsFire)

allfuels <- allfuels %>% 
  select(plot_id, location, mass, fuel_size) %>% 
  na.omit()

treatment_all <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/data/all_location_treatment.csv")
allfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/data/allfuels.csv")
allfuel_treatment <- left_join(allfuels,treatment_all, by = "plot_id")



```


# Pre-fire fuels comparions across sites

```{r}


###CREATE TOTAL FUEL LOAD COLUMN
                        
                        allfuels_sum <- allfuels %>% 
                          pivot_wider(names_from = fuel_size,
                                      values_from = mass) %>% 
                           mutate_all(~replace(., is.na(.), 0)) %>% 
                          group_by(plot_id) %>% 
                          mutate(total_fuel = sum(mass_1hr,mass_10hr,mass_100hr,mass_cwd_sound, mass_cwd_rotten)) %>% 
                            mutate(plot_id_location = paste(plot_id, location)) 
                        
                        allfuels_complete <- allfuels_sum %>% 
                            group_by(plot_id_location) %>% 
                            select(plot_id_location, mass_1hr, mass_10hr, mass_100hr, mass_cwd_sound, mass_cwd_rotten, total_fuel) %>% 
                              pivot_longer(-plot_id_location, names_to = "fuel_size", values_to = "mass") %>% 
                              separate(plot_id_location, c("plot_id", "location"), sep=" ") 
                          allfuels_complete <-left_join(allfuels_complete,treatment_all, by = "plot_id")

                        
                        
export(allfuels_complete, "C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/data/allfuels_complete.csv")
allfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/data/allfuels.csv")

bearmtn_plot_fuels <- allfuels_complete %>% 
            filter(location.x=='BearMtn')  
bearmtn_fuels_total <- bearmtn_plot_fuels %>% 
  filter(fuel_size == 'total_fuel')
mean(bearmtn_fuels_total$mass)
bearmtn_plot_fuels <- ggplot(data=bearmtn_plot_fuels, mapping = aes(x=burnunit, y=mass, fill=burnunit))+
              geom_boxplot()+
              facet_wrap(~ fuel_size, scales = "free_y") +
              theme_minimal()+
              xlab("burn unit")+
              ylab("Mass(Tons/Acre)")+
              ggtitle("Bear Mountain Stanislaus National Forest")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
 bearmtn_plot_fuels
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/bearmtn_fuels.png", bearmtn_plot_fuels)
 
 frenchmeadows_plot_fuels <- allfuels_complete %>% 
            filter(location.x=='FrenchMeadows')  
 fm_fuels_total <- frenchmeadows_plot_fuels %>% 
  filter(fuel_size == 'total_fuel')
mean(fm_fuels_total$mass)
 FM_plot_fuels <- ggplot(data=frenchmeadows_plot_fuels, mapping = aes(x=burnunit, y=mass, fill=burnunit))+
              geom_boxplot()+
              facet_wrap(~ fuel_size, scales = "free_y") +
              theme_minimal()+
              xlab("burn unit")+
              ylab("Mass(Tons/Acre)")+
              ggtitle("French Meadows")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
 FM_plot_fuels
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/FM_fuels.png", FM_plot_fuels)

 
   lakes_plot_fuels <- allfuels_complete %>% 
            filter(location.x=='LakesDistrict')  
    lakes_fuels_total <- lakes_plot_fuels %>% 
  filter(fuel_size == 'total_fuel')
mean(lakes_fuels_total$mass)
 lakes_plot_fuels <- ggplot(data=lakes_plot_fuels, mapping = aes(x=burnunit, y=mass, fill=burnunit))+
              geom_boxplot()+
              facet_wrap(~ fuel_size, scales = "free_y") +
              theme_minimal()+
              xlab("burn unit")+
              ylab("Mass(Tons/Acre)")+
              ggtitle("Lakes District - Bliss and Burton State Parks")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
 lakes_plot_fuels
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/lakes_fuels.png", lakes_plot_fuels)

 
    slypark_fuels <- allfuels_complete %>% 
            filter(location.x=='SlyPark')  
     slypark_fuels_total <- slypark_fuels %>% 
  filter(fuel_size == 'total_fuel')
mean(slypark_fuels_total$mass)
 slypark_fuels <- ggplot(data=slypark_fuels, mapping = aes(x=burnunit, y=mass, fill=burnunit))+
              geom_boxplot()+
              facet_wrap(~ fuel_size, scales = "free_y") +
              theme_minimal()+
              xlab("burn unit")+
              ylab("Mass(Tons/Acre)")+
              ggtitle("Sly Park")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
 slypark_fuels
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/slypark_fuels.png", slypark_fuels)
 
 
  
    springs_fuels <- allfuels_complete %>% 
            filter(location.x=='SpringsFire')  
     springs_fuels_total <- springs_fuels %>% 
  filter(fuel_size == 'total_fuel')
mean(springs_fuels_total$mass)
 springs_fuels <- ggplot(data=springs_fuels, mapping = aes(x=burnunit, y=mass, fill=burnunit))+
              geom_boxplot()+
              facet_wrap(~ fuel_size, scales = "free_y") +
              theme_minimal()+
              xlab("burn unit")+
              ylab("Mass(Tons/Acre)")+
              ggtitle("Springs Fire")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              theme(plot.title = element_text(hjust = 0.5))
 springs_fuels
ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/springs_fuels.png", springs_fuels)
 
```


# Pre-fire Trees


```{r}
#all standing

                
                PreBurn_BMtrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/clean/BM_trees_standing.csv")
                PreBurn_BMtrees <- PreBurn_BMtrees %>% 
                  mutate(location = 'BearMtn')
                
                                    #Total tree density live
                                          PreBurn_BM_livetree <- PreBurn_BMtrees %>% 
                                            filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(total_trees_acre = sum(total_trees_acre),
                                                      mean_dbh = mean(mean_dbh),
                                                      mean_ht = mean(mean_ht))
                     
                                             mean(PreBurn_BM_livetree$total_trees_acre)
                                             mean(PreBurn_BM_livetree$mean_dbh)
                                             mean(PreBurn_BM_livetree$mean_ht)
                
                PreBurn_FMtrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/French_Meadows/data/clean/FM_trees_standing.csv")
                PreBurn_FMtrees <- PreBurn_FMtrees %>% 
                  mutate(location = 'FrenchMeadows')
                
                 #Total tree density live
                                          PreBurn_FM_livetree <- PreBurn_FMtrees %>% 
                                            filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(total_trees_acre = sum(total_trees_acre),
                                                      mean_dbh = mean(mean_dbh),
                                                      mean_ht = mean(mean_ht))
                     
                                             mean(PreBurn_FM_livetree$total_trees_acre)
                                             mean(PreBurn_FM_livetree$mean_dbh)
                                             mean(PreBurn_FM_livetree$mean_ht)
                
                
                PreBurn_lakestrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Lakes_District/data/clean/prelakesdistrict_trees_standing.csv")
                PreBurn_lakestrees <- PreBurn_lakestrees %>% 
                  mutate(location = 'LakesDistrict')
                
                 #Total tree density live
                                          PreBurn_lakes_livetree <- PreBurn_lakestrees %>% 
                                            filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(total_trees_acre = sum(total_trees_acre))
                     
                                             mean(PreBurn_lakes_livetree$total_trees_acre)
                
                PreBurn_SlyParktrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Sly_Park/data/clean/SlyPark_trees_standing.csv")
                PreBurn_SlyParktrees <- PreBurn_SlyParktrees %>% 
                  mutate(location = 'SlyPark')
                
                #Total tree density live
                                          PreBurn_slypark_livetree <- PreBurn_SlyParktrees %>% 
                                            filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(total_trees_acre = sum(total_trees_acre))
                     
                                             mean(PreBurn_slypark_livetree$total_trees_acre)
                
                PreBurn_SpringsFiretrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/prespringstrees_standing.csv")
                PreBurn_SpringsFiretrees <- PreBurn_SpringsFiretrees %>% 
                  mutate(location = 'SpringsFire')

                  alltrees <- bind_rows(PreBurn_BMtrees, PreBurn_FMtrees , PreBurn_lakestrees, PreBurn_SlyParktrees, PreBurn_SpringsFiretrees)
                  
                  alltrees <- alltrees %>% 
                    select(location, plot_id, species_id, status, mean_dbh, mean_ht, total_trees_acre, location ) %>% 
                    mutate(diameter_class_cm = case_when(
                           mean_dbh < 11.5 ~ "<11.5" ,
                          mean_dbh < 25.3 ~ "11.5-25.3",
                          mean_dbh < 45.6 ~ "25.3-45.6",
                          mean_dbh < 76.2 ~ "45.6-76.2",
                          TRUE ~ ">76.2"
                    )) 
                  str(alltrees)
                  alltrees$diameter_class_cm <- as.character(alltrees$diameter_class_cm)

  ##PLOT ALL TREES DBH LIVE AND DEAD

                     alltrees_total <- ggplot(data=alltrees, mapping = aes(x=location, y=total_trees_acre, fill= diameter_class_cm))+
                                  geom_boxplot()+
                                  facet_wrap(~status,scales = "free_y")+
                                  theme_minimal()+
                                  xlab("Location")+
                                  ylab("Total Trees/ Acre")+
                                  theme(axis.text.x = element_text(angle=45, hjust=1))+
                                  theme(plot.title = element_text(hjust = 0.5))
                     alltrees_total
                      ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/alltrees_total.png", alltrees_total)


### PLOT JUST LIVE TREES
             livetrees <- alltrees %>% 
               filter(status == "live") 
 
              alltrees_live_class <- ggplot(data=livetrees, mapping = aes(x=location, y=total_trees_acre, fill= diameter_class_cm))+
                          geom_boxplot(width=0.75)+
                         
                          facet_wrap(~status,scales = "free_y")+
                          theme_minimal()+
                          xlab("Location")+
                          ylab("Total Live Trees/ Acre")+
                          theme(axis.text.x = element_text(angle=45, hjust=1))+
                          theme(plot.title = element_text(hjust = 0.5))
                alltrees_live_class
 

 
 
 
         ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/alltrees_live_class.png", alltrees_live_class)
 
         
### Plot all live trees by species
                                   
                           livetrees <- alltrees %>% 
                             filter(status == "live") %>% 
                             filter(species_id == "abco" | species_id == "abma" |species_id == "cade"|species_id == "pico"|species_id == "pije"|species_id == "pila"|species_id == "pimo"|species_id == "pipo"|species_id == "psme"|species_id == "quch"|species_id == "quke")
                           
                           str(livetrees) 
 
               alltrees_live <-  ggplot(data=livetrees, mapping = aes(x=location, y=total_trees_acre, fill=species_id))+
                            geom_boxplot(lwd=0.5)+
                          coord_cartesian(ylim = c(0,600))+
                          scale_fill_brewer(palette = "Spectral")+
                            theme_minimal()+
                            xlab("Location")+
                            ylab("Total trees/acre")+
                            theme(axis.text.x = element_text(angle=45, hjust=1))+
                            theme(plot.title = element_text(hjust = 0.5))

alltrees_live
ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/alltrees_live.png", alltrees_live)





```


# Pre-fire Basal Area

```{r}

BM_basalarea_complete <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/clean/BM_basalarea_complete.csv")
BM_basalarea_complete <- BM_basalarea_complete %>% 
  mutate(location = 'BearMtn')

#Avg basal area stand (ft^2/acre)
                                          BM_basalarea_avg <- BM_basalarea_complete %>% 
                                             filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(avg_ba = mean(stand_ba))
                     
                                             mean(BM_basalarea_avg$avg_ba)

FM_basalarea_complete <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/French_Meadows/data/clean/FMbasalarea_complete.csv")
FM_basalarea_complete <- FM_basalarea_complete %>% 
  mutate(location = 'FrenchMeadows')

#Avg basal area stand (ft^2/acre)
                                          FM_basalarea_avg <- FM_basalarea_complete %>% 
                                            filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(avg_ba = mean(stand_ba))
                     
                                             mean(FM_basalarea_avg$avg_ba)


Lakes_basalarea_complete <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Lakes_District/data/clean/prelakesbasalarea_complete.csv")
Lakes_basalarea_complete <- Lakes_basalarea_complete %>% 
  mutate(location = 'LakesDistrict')

#Avg basal area stand (ft^2/acre)
                                          lakes_basalarea_avg <- Lakes_basalarea_complete %>% 
                                            filter(status == "live") %>% 
                                            group_by(plot_id) %>% 
                                            summarize(avg_ba = mean(stand_ba))
                     
                                             mean(FM_basalarea_avg$avg_ba)

SlyPark_basalarea <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Sly_Park/data/clean/SlyParkbasalarea_complete.csv")
SlyPark_basalarea <- SlyPark_basalarea %>% 
  mutate(location = 'SlyPark')

BasalArea_SpringsFire <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/prespringsbasalarea_complete.csv")
BasalArea_SpringsFire <- BasalArea_SpringsFire %>% 
  mutate(location = 'SpringsFire')

allbasalarea <- bind_rows(FM_basalarea_complete, Lakes_basalarea_complete, SlyPark_basalarea, BasalArea_SpringsFire, BM_basalarea_complete)

allbasalarea <- allbasalarea %>% 
  select(plot_id, location, stand_ba, status, species_id) %>% 
  na.omit()

allbasalarea <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/Data/allbasalarea.csv")

 basalarea_byspecies <- ggplot(data=allbasalarea, mapping = aes(x=location, y=stand_ba, fill= species_id))+
        scale_fill_brewer(palette = "Spectral")+
                         geom_boxplot()+
              geom_jitter(alpha = 0.1)+
              facet_wrap(~ status, scales = "free_y") +
              theme_minimal()+
              xlab("Location")+
              ylab("Initial Stand Basal Area (ft^2/acre)")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              ggtitle("Initial Stand Basal Area by Species")+
              theme(plot.title = element_text(hjust = 0.5))

 
  basalarea_live <- allbasalarea %>% 
    filter(status == "live")
  
  ggplot(data=basalarea_live, mapping = aes(x=location, y=stand_ba, fill=species_id))+
       geom_boxplot()+
     scale_fill_brewer(palette = "Spectral")+
              geom_jitter(alpha = 0.1)+
              
              theme_minimal()+
              xlab("Location")+
              ylab("Initial Stand Basal Area (ft^2/acre)")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              ggtitle("Initial Stand Basal Area by Species")+
              theme(plot.title = element_text(hjust = 0.5))
  basalarea_byspecies
 
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/basalarea_avg.png",  basalarea_avg)
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/basalarea_byspp.png",  basalarea_byspecies)


```

#LITTER AND DUFF CONSUMPTION


```{r}

PreBurn_BM_LD <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/clean/pre_BearMtn_litterduff.csv")
PreBurn_BM_LD <- PreBurn_BM_LD %>% 
  mutate(location = 'BearMtn')

   BM_LD_litter <- PreBurn_BM_LD %>% 
        filter(litter_duff == 'mean_litter') %>% 
        na.omit()
      mean(BM_LD_litter$depth_cm)
      BM_LD_duff <- PreBurn_BM_LD %>% 
        filter(litter_duff == 'mean_duff') %>% 
        na.omit()
      mean(BM_LD_duff$depth_cm)
      

FMfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/French_Meadows/data/raw/FrenchMeadows_finefuels.csv")
FMfuels <- FMfuels %>% 
  mutate(location = 'FrenchMeadows')

FM_LD <- FMfuels %>% 
         mutate(litter_depth_cm = ((litter1_cm + litter2)/2)) %>% 
        mutate(duff_depth_cm = ((duff1_cm+duff2_cm)/2)) %>% 
                  select(plot_id, duff_depth_cm, litter_depth_cm) %>% 
                  group_by(plot_id) %>% 
                   summarize(mean_litter = mean(litter_depth_cm),
                         mean_duff = mean(duff_depth_cm)) %>% 
                  pivot_longer(-plot_id, names_to = "litter_duff", values_to = "depth_cm")
                export(FM_LD, "C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/French_Meadows/data/clean/FM_litterduff.csv")
                
  FM_LD <- FM_LD %>% 
    mutate(location = 'FrenchMeadows')
      FM_LD_litter <- FM_LD %>% 
        filter(litter_duff == 'mean_litter')
      mean(FM_LD_litter$depth_cm)
      FM_LD_duff <- FM_LD %>% 
        filter(litter_duff == 'mean_duff')
      mean(FM_LD_duff$depth_cm)
      


PreBurn_lakesfuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Lakes_District/data/raw/LakesDistrict_finefuels.csv")
PreBurn_lakesfuels <- PreBurn_lakesfuels %>% 
  mutate(location = 'LakesDistrict')

Lakes_LD <- PreBurn_lakesfuels %>% 
         mutate(litter_depth_cm = ((litter1_cm + litter2_cm)/2)) %>% 
        mutate(duff_depth_cm = ((duff1_cm+duff2_cm)/2)) %>% 
                  select(plot_id, duff_depth_cm, litter_depth_cm) %>% 
                  group_by(plot_id) %>% 
                   summarize(mean_litter = mean(litter_depth_cm),
                         mean_duff = mean(duff_depth_cm)) %>% 
                  pivot_longer(-plot_id, names_to = "litter_duff", values_to = "depth_cm")
                export(FM_LD, "C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Lakes_District/data/clean/Lakes_litterduff.csv")
                
                 lakes_LD_litter <- Lakes_LD %>% 
        filter(litter_duff == 'mean_litter') %>% 
                   na.omit()
      mean(lakes_LD_litter$depth_cm)
      lakes_LD_duff <- Lakes_LD %>% 
        filter(litter_duff == 'mean_duff') %>% 
        na.omit()
      mean(lakes_LD_duff$depth_cm)
      
      
      Lakes_LD <- Lakes_LD %>% 
        mutate(location = 'LakesDistrict')
                
                
                
PreBurn_SlyParkFuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Sly_Park/data/raw/SlyPark_finefuels.csv")
PreBurn_SlyParkFuels <- PreBurn_SlyParkFuels %>% 
  mutate(location = 'SlyPark')

SlyPark_LD <- PreBurn_SlyParkFuels %>% 
         mutate(litter_depth_cm = ((litter1_cm + litter2_cm)/2)) %>% 
        mutate(duff_depth_cm = ((duff1_cm+duff2_cm)/2)) %>% 
                  select(plot_id, duff_depth_cm, litter_depth_cm) %>% 
                  group_by(plot_id) %>% 
                   summarize(mean_litter = mean(litter_depth_cm),
                         mean_duff = mean(duff_depth_cm)) %>% 
                  pivot_longer(-plot_id, names_to = "litter_duff", values_to = "depth_cm")
                export(SlyPark_LD, "C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Sly_Park/data/clean/SlyPark_litterduff.csv")
                
                 SlyPark_LD_litter <- SlyPark_LD %>% 
        filter(litter_duff == 'mean_litter') %>% 
                   na.omit()
      mean(SlyPark_LD_litter$depth_cm)
      SlyPark_LD_duff <- SlyPark_LD %>% 
        filter(litter_duff == 'mean_duff') %>% 
        na.omit()
      mean(SlyPark_LD_duff$depth_cm)
      
      SlyPark_LD <- SlyPark_LD %>% 
        mutate(location = 'SlyPark')

PreSprings_LD <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/clean/pre_springs_litterduff.csv")
 Springs_LD_litter <- PreSprings_LD %>% 
        filter(litter_duff == 'mean_litter') %>% 
                   na.omit()
      mean(Springs_LD_litter$depth_cm)
      Springs_LD_duff <- PreSprings_LD %>% 
        filter(litter_duff == 'mean_duff') %>% 
        na.omit()
      mean(Springs_LD_duff$depth_cm)
      
      PreSprings_LD <- PreSprings_LD %>% 
        mutate(location = 'SpringsFire')
      
      
      all_litterduff <-   bind_rows(PreSprings_LD, SlyPark_LD, Lakes_LD, FM_LD, PreBurn_BM_LD)
      all_litterduff <- all_litterduff %>% 
        na.omit()
      
      all_LD <-   ggplot(data=all_litterduff, mapping = aes(x=location, y=depth_cm, fill=litter_duff))+
              geom_boxplot()+
             
              theme_minimal()+
              xlab("Duff and Litter consumption")+
              ylab("Depth (cm)")+
              scale_fill_manual(values=c("#69b3a2", "#404080"))+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
             
              theme(plot.title = element_text(hjust = 0.5))
      all_LD            
      
      ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/all_litterduff.png", all_LD)
      
      all_LD <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/all_litterduff.png")

      
```




# BASAL AREA WITH TREE DATA!!!!!

```{r}

#Springs BA

                    PreBA_SpringsFiretrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Springs_Fire/data/raw/pre_springsfire_trees.csv")
                    
                    PreBA_SpringsFiretrees <- PreBA_SpringsFiretrees %>% 
                        select(plot_id, status, dbm_cm, site) %>% 
                        filter(status =="live"|status=="dead") %>% 
                       mutate(dbh_ft = dbm_cm*0.03281) %>% 
                      mutate(basalarea_sqft = pi * (dbh_ft/2)^2) %>% 
                      mutate(basalarea_sqft_acre = basalarea_sqft*10)
                      
                    
                    
                    Springs_BA_sum <- PreBA_SpringsFiretrees %>% 
                      group_by(plot_id, status) %>% 
                      summarise(BA_sum_sqft_acre = sum(basalarea_sqft_acre))
                    
                      Springs_BA_sum_live <- Springs_BA_sum %>% 
                      filter(status=="live") 
                    
                    mean(Springs_BA_sum$BA_sum_sqft_acre)
                   mean(Springs_BA_sum_live$BA_sum_sqft_acre)
                    
 #BM BA

                    PreBA_BMtrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/raw/pre_BearMtn_Trees.csv")
                    
                    PreBA_BMtrees <- PreBA_BMtrees %>% 
                        select(plot_id, status, dbh_cm, Site) %>% 
                        rename(site = 'Site') %>% 
                        filter(status =="live"|status=="dead") %>% 
                       mutate(dbh_ft = dbh_cm*0.03281) %>% 
                      mutate(basalarea_sqft = pi * (dbh_ft/2)^2) %>% 
                      mutate(basalarea_sqft_acre = basalarea_sqft*10)
                      
                    
                    
                    BM_BA_sum <- PreBA_BMtrees %>% 
                      group_by(plot_id, status) %>% 
                      summarise(BA_sum_sqft_acre = sum(basalarea_sqft_acre))
                    
                    BM_BA_sum_live <- BM_BA_sum %>% 
                      filter(status=="live") 
                    
                    mean(BM_BA_sum$BA_sum_sqft_acre)
                   mean(BM_BA_sum_live$BA_sum_sqft_acre)
                   
                   
   #FM BA

                    PreBA_FMtrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/French_Meadows/data/raw/FrenchMeadows_Trees.csv")
                    
                    PreBA_FMtrees <- PreBA_FMtrees %>% 
                        select(plot_id, status, dbh_cm, site) %>% 
                       
                        filter(status =="live"|status=="dead") %>% 
                       mutate(dbh_ft = dbh_cm*0.03281) %>% 
                      mutate(basalarea_sqft = pi * (dbh_ft/2)^2) %>% 
                      mutate(basalarea_sqft_acre = basalarea_sqft*10)
                      
                    
                    
                    FM_BA_sum <- PreBA_FMtrees %>% 
                      group_by(plot_id, status) %>% 
                      summarise(BA_sum_sqft_acre = sum(basalarea_sqft_acre))
                    
                    FM_BA_sum_live <- FM_BA_sum %>% 
                      filter(status=="live") 
                    
                    mean(FM_BA_sum$BA_sum_sqft_acre, na.rm=TRUE)
                   mean(FM_BA_sum_live$BA_sum_sqft_acre)
                   
          #lakes BA

                    PreBA_lakestrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Lakes_District/data/raw/LakesDistrict_trees.csv")
                    
                    PreBA_lakestrees <- PreBA_lakestrees %>% 
                        select(plot_id, status, dbh_cm, site) %>% 
                        filter(status =="live"|status=="dead") %>% 
                       mutate(dbh_ft = dbh_cm*0.03281) %>% 
                      mutate(basalarea_sqft = pi * (dbh_ft/2)^2) %>% 
                      mutate(basalarea_sqft_acre = basalarea_sqft*10)
                      
                    
                    
                    lakes_BA_sum <- PreBA_lakestrees %>% 
                      group_by(plot_id, status) %>% 
                      summarise(BA_sum_sqft_acre = sum(basalarea_sqft_acre))
                    
                    lakes_BA_sum_live <- lakes_BA_sum %>% 
                      filter(status=="live") 
                    
                    mean(lakes_BA_sum$BA_sum_sqft_acre, na.rm=TRUE)
                   mean(lakes_BA_sum_live$BA_sum_sqft_acre, na.rm = TRUE)
                   
                   
          #Sly Park BA
                   
                   PreBA_slyparktrees <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Sly_Park/data/raw/SlyPark_Trees.csv")
                    
                    PreBA_slyparktrees <- PreBA_slyparktrees %>% 
                        select(plot_id, status, dbh_cm, Site) %>% 
                      rename(site = 'Site') %>% 
                        filter(status =="live"|status=="dead") %>% 
                       mutate(dbh_ft = dbh_cm*0.03281) %>% 
                      mutate(basalarea_sqft = pi * (dbh_ft/2)^2) %>% 
                      mutate(basalarea_sqft_acre = basalarea_sqft*10)
                      
                    
                    
                    slypark_BA_sum <- PreBA_slyparktrees %>% 
                      group_by(plot_id, status) %>% 
                      summarise(BA_sum_sqft_acre = sum(basalarea_sqft_acre))
                    
                    slypark_BA_sum_live <- slypark_BA_sum %>% 
                      filter(status=="live") 
                    
                    mean(slypark_BA_sum$BA_sum_sqft_acre, na.rm=TRUE)
                   mean(slypark_BA_sum_live$BA_sum_sqft_acre, na.rm = TRUE)
                   
                   
##PLOT ALL                   
                   
                   
 allbasalarea <- bind_rows(PreBA_slyparktrees, PreBA_lakestrees , PreBA_FMtrees, PreBA_BMtrees, PreBA_SpringsFiretrees)

allbasalarea <- allbasalarea %>% 
  select(plot_id, site, basalarea_sqft_acre, status) %>% 
  na.omit() %>% 
  group_by(site, plot_id, status) %>% 
  summarise(BA_sum_sqft_acre = sum(basalarea_sqft_acre))

 export(allbasalarea, "C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/Data/allbasalarea.csv")

 basalarea_bystatus <- ggplot(data=allbasalarea, mapping = aes(x=site, y=BA_sum_sqft_acre, fill= status))+
       
              geom_boxplot()+
              scale_fill_manual(values=c( "#404080","#69b3a2"))+
              theme_minimal()+
              xlab("Location")+
              ylab("Initial Stand Basal Area (ft^2/acre)")+
              theme(axis.text.x = element_text(angle=45, hjust=1))+
              
              theme(plot.title = element_text(hjust = 0.5))
 basalarea_bystatus
 
 ggsave("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/2020_AnnualReport/results/alltrees_basalarea_status.png", basalarea_bystatus)


 
 
 

```


```{r}

PostBearFuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/clean/post_BearMtnFuelscomplete.csv")
BearFuels <- import("C:/Users/ashle/Documents/R/RX_Fire_Monitoring/RX_Fire_Monitoring/Bear_Mtn/data/clean/BearMtnfuelsComplete.csv")

BearFuels_sum <- BearFuels %>% 
                          pivot_wider(names_from = fuel_size,
                                      values_from = mass) %>% 
                                          group_by(plot_id) %>% 
                          mutate(total_fuel = sum(mass_1hr,mass_10hr,mass_100hr,mass_cwd_sound, mass_cwd_rotten)) %>% 
                          mutate(plot_id_time = paste(plot_id, time))
                           

BMfuels_complete <- BearFuels_sum %>% 
                            group_by(plot_id_time) %>% 
                            select(plot_id_time, mass_1hr, mass_10hr, mass_100hr, mass_cwd_sound, mass_cwd_rotten, total_fuel) %>% 
                              pivot_longer(-plot_id_time, names_to = "fuel_size", values_to = "mass") %>% 
                              separate(plot_id_time, c("plot_id", "time"), sep=" ") 

BMfuels_total <- BMfuels_complete %>% 
          filter(time == 'preburn_mass') %>% 
          filter(fuel_size == 'total_fuel')
mean(BMfuels_total$mass)




```





























